// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's profile: name, role, team, age category, subscription tier and approval status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "user_id, display_name, role, team, position, age, age_category, subscription_tier, payment_status, is_approved, courtiq_enabled"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this user." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-shot-sessions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_shot_sessions_default = defineTool2({
  name: "list_shot_sessions",
  title: "List shooting sessions",
  description: "List shooting (Shot Tracker) sessions visible to the signed-in user, with makes, attempts and shooting percentage per session.",
  inputSchema: {
    player_id: z.string().uuid().optional().describe("Optional player id. Coaches can pass a player id; players see only their own sessions."),
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of sessions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ player_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("shot_sessions").select("id, title, date, notes, player_id, shots(zone, shot_type, made, attempts)").order("date", { ascending: false }).limit(limit ?? 20);
    if (player_id) query = query.eq("player_id", player_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const sessions = (data ?? []).map((session) => {
      const shots = session.shots ?? [];
      const made = shots.reduce((sum, s) => sum + (s.made ?? 0), 0);
      const attempts = shots.reduce((sum, s) => sum + (s.attempts ?? 0), 0);
      return {
        id: session.id,
        title: session.title,
        date: session.date,
        notes: session.notes,
        player_id: session.player_id,
        made,
        attempts,
        percentage: attempts > 0 ? Math.round(made / attempts * 100) : 0,
        by_zone: shots
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(sessions) }],
      structuredContent: { sessions }
    };
  }
});

// src/lib/mcp/tools/list-video-sessions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_video_sessions_default = defineTool3({
  name: "list_video_sessions",
  title: "List video analysis sessions",
  description: "List game / video analysis sessions visible to the signed-in user, including box-score stats and the overall analysis score.",
  inputSchema: {
    player_id: z2.string().uuid().optional().describe("Optional player id (coaches only)."),
    limit: z2.number().int().min(1).max(100).default(20).describe("Maximum number of sessions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ player_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("sessions").select(
      "id, date, opponent, status, points, assists, rebounds, steals, turnovers, fg_percentage, overall_score, coach_notes, player_id"
    ).order("date", { ascending: false }).limit(limit ?? 20);
    if (player_id) query = query.eq("player_id", player_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-player-goals.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_player_goals_default = defineTool4({
  name: "list_player_goals",
  title: "List player goals",
  description: "List training goals visible to the signed-in user, with progress percentage and status.",
  inputSchema: {
    player_id: z3.string().uuid().optional().describe("Optional player id (coaches only)."),
    status: z3.enum(["active", "completed"]).optional().describe("Filter by goal status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ player_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("player_goals").select("id, title, description, category, progress, status, target_date, progress_notes, player_id").order("created_at", { ascending: false });
    if (player_id) query = query.eq("player_id", player_id);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { goals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-courtiq-stats.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_courtiq_stats_default = defineTool5({
  name: "get_courtiq_stats",
  title: "Get Court IQ stats",
  description: "Get Court IQ trivia stats (points, streaks, correct answers) for the signed-in user or a given player.",
  inputSchema: {
    player_id: z4.string().uuid().optional().describe("Optional player id (coaches only). Defaults to the signed-in user.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ player_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("courtiq_player_stats").select("*").eq("player_id", player_id ?? ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No Court IQ stats yet." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { stats: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mzlakkhodbqdhamjrhah";
var mcp_default = defineMcp({
  name: "count-my-shots",
  title: "count my shots",
  version: "0.1.0",
  instructions: "Tools for the count my shots basketball analytics app. Read the signed-in user's profile, shooting sessions and totals, video analysis sessions, training goals and Court IQ trivia stats. Coaches may pass a player_id to read their players' data; players always see only their own.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_shot_sessions_default,
    list_video_sessions_default,
    list_player_goals_default,
    get_courtiq_stats_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
